apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-27T06:54:22Z"
  labels:
    app: acm-cplex-solver
  name: acm-cplex-solver-svc
  namespace: acm-production
  resourceVersion: "24797511"
  uid: eee2ea48-415a-4fed-96e6-6615ddac3bd3
spec:
  clusterIP: 10.102.207.60
  clusterIPs:
  - 10.102.207.60
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32312
    port: 80
    protocol: TCP
    targetPort: 50051
  selector:
    app: acm-cplex-solver
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
