apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-27T06:54:29Z"
  labels:
    app: acm-web
  name: acm-web-svc
  namespace: acm-production
  resourceVersion: "24702326"
  uid: 396cf53d-0354-4366-b531-bb4fc40ad168
spec:
  clusterIP: 10.98.75.84
  clusterIPs:
  - 10.98.75.84
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30721
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: acm-web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
