apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-27T06:54:21Z"
  labels:
    app: acm-api
  name: acm-api-svc
  namespace: acm-production
  resourceVersion: "24697543"
  uid: 06af2f87-41be-4760-8cb1-94c971666506
spec:
  clusterIP: 10.97.50.128
  clusterIPs:
  - 10.97.50.128
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30185
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: acm-api
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
