apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
  creationTimestamp: "2023-02-27T06:54:21Z"
  labels:
    app: acmapis
  name: acmapis-svc
  namespace: acm-production
  resourceVersion: "23565887"
  uid: 2a018b7a-4f1a-4a35-a47f-1583192c2b76
spec:
  clusterIP: 10.97.57.202
  clusterIPs:
  - 10.97.57.202
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31076
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: acmapis
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
