apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
  creationTimestamp: "2023-02-27T06:54:21Z"
  labels:
    app: acmadmin-api
  name: acmadmin-api-svc
  namespace: acm-production
  resourceVersion: "23565859"
  uid: a47e1fd5-2fdc-4fff-8a7d-c2233e0814df
spec:
  clusterIP: 10.100.160.141
  clusterIPs:
  - 10.100.160.141
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32082
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: acmadmin-api
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
