apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-27T06:54:21Z"
  labels:
    app: acmadp
  name: acmadp-svc
  namespace: acm-production
  resourceVersion: "27585734"
  uid: c200dd3b-ea1e-4773-be83-93196c506176
spec:
  clusterIP: 10.107.85.81
  clusterIPs:
  - 10.107.85.81
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32168
    port: 80
    protocol: TCP
    targetPort: 10055
  selector:
    app: acmadp
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
