apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
  creationTimestamp: "2023-02-27T06:54:21Z"
  labels:
    app: acmadmin
  name: acmadmin-svc
  namespace: acm-production
  resourceVersion: "23565864"
  uid: 28a842da-86ce-4c33-9c43-eace587caf75
spec:
  clusterIP: 10.100.29.241
  clusterIPs:
  - 10.100.29.241
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32217
    port: 80
    protocol: TCP
    targetPort: 10052
  selector:
    app: acmadmin
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
