apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-27T06:54:22Z"
  labels:
    app: acmbase
  name: acmbase-svc
  namespace: acm-production
  resourceVersion: "24698029"
  uid: 5f225ec5-11ea-4dce-8aa1-685378dcc685
spec:
  clusterIP: 10.99.146.160
  clusterIPs:
  - 10.99.146.160
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32679
    port: 80
    protocol: TCP
    targetPort: 11062
  selector:
    app: acmbase
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
