apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-27T06:54:22Z"
  labels:
    app: acmcaptive-web
  name: acmcaptive-web-svc
  namespace: acm-production
  resourceVersion: "24699357"
  uid: ded8ea11-f67a-436c-8966-b4863e8cdc8e
spec:
  clusterIP: 10.108.35.37
  clusterIPs:
  - 10.108.35.37
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31893
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: acmcaptive-web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
