apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
  creationTimestamp: "2023-02-27T06:54:22Z"
  labels:
    app: acmcaptive-v2-web
  name: acmcaptive-v2-web-svc
  namespace: acm-production
  resourceVersion: "23565912"
  uid: a8eeb2b1-28c8-4987-8fc1-ac8aa1307c8f
spec:
  clusterIP: 10.106.212.135
  clusterIPs:
  - 10.106.212.135
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31559
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: acmcaptive-v2-web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
