apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-27T06:54:22Z"
  labels:
    app: acmcampaign
  name: acmcampaign-svc
  namespace: acm-production
  resourceVersion: "24791788"
  uid: ecd3e420-72de-44c2-b4f3-f348e7fa0dec
spec:
  clusterIP: 10.104.83.152
  clusterIPs:
  - 10.104.83.152
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30644
    port: 80
    protocol: TCP
    targetPort: 10054
  selector:
    app: acmcampaign
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
