apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
  creationTimestamp: "2023-02-27T06:54:22Z"
  labels:
    app: acmcampaignmatchrate
  name: acmcampaignmatchrate-svc
  namespace: acm-production
  resourceVersion: "23565902"
  uid: 7c27d535-c562-41eb-a0d9-1a82bfef9010
spec:
  clusterIP: 10.110.74.52
  clusterIPs:
  - 10.110.74.52
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32424
    port: 80
    protocol: TCP
    targetPort: 10069
  selector:
    app: acmcampaignmatchrate
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
