apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
  creationTimestamp: "2023-02-27T06:54:23Z"
  labels:
    app: acmdirectory
  name: acmdirectory-svc
  namespace: acm-production
  resourceVersion: "23565927"
  uid: 1b08c986-5f1d-4187-b952-1bc8d487574b
spec:
  clusterIP: 10.106.169.53
  clusterIPs:
  - 10.106.169.53
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31752
    port: 80
    protocol: TCP
    targetPort: 11058
  selector:
    app: acmdirectory
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
