apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
  creationTimestamp: "2023-02-27T06:54:23Z"
  labels:
    app: acmid
  name: acmid-svc
  namespace: acm-production
  resourceVersion: "23565939"
  uid: 9fa0ffea-2a17-4faf-a420-8acae6c945e4
spec:
  clusterIP: 10.110.183.176
  clusterIPs:
  - 10.110.183.176
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31292
    port: 80
    protocol: TCP
    targetPort: 10051
  selector:
    app: acmid
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
