apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-27T06:54:23Z"
  labels:
    app: acmid-web
  name: acmid-web-svc
  namespace: acm-production
  resourceVersion: "23595751"
  uid: 51260f27-d0e1-45de-86a5-79207eb40275
spec:
  clusterIP: 10.110.210.197
  clusterIPs:
  - 10.110.210.197
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32125
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: acmid-web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
