apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
  creationTimestamp: "2023-02-27T06:54:23Z"
  labels:
    app: acmplacestatsforecast
  name: acmplacestatsforecast-svc
  namespace: acm-production
  resourceVersion: "23565949"
  uid: 7c4321e1-9de7-4e07-97a2-a9a9d74c7fb2
spec:
  clusterIP: 10.104.245.53
  clusterIPs:
  - 10.104.245.53
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30073
    port: 80
    protocol: TCP
    targetPort: 10059
  selector:
    app: acmplacestatsforecast
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
