apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
  creationTimestamp: "2023-02-27T06:54:23Z"
  labels:
    app: acmremarketing
  name: acmremarketing-svc
  namespace: acm-production
  resourceVersion: "23565959"
  uid: 9353dd98-a7e6-44de-bf96-1022b51e4f9e
spec:
  clusterIP: 10.109.68.55
  clusterIPs:
  - 10.109.68.55
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31764
    port: 80
    protocol: TCP
    targetPort: 11066
  selector:
    app: acmremarketing
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
