apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-27T06:54:28Z"
  labels:
    app: acmsaga
  name: acmsaga-svc
  namespace: acm-production
  resourceVersion: "24701603"
  uid: 70150e62-88c5-425e-b17c-aaa9a2fc72fe
spec:
  clusterIP: 10.109.62.172
  clusterIPs:
  - 10.109.62.172
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30374
    port: 80
    protocol: TCP
    targetPort: 11056
  selector:
    app: acmsaga
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
