apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-27T06:54:28Z"
  labels:
    app: acmschedule
  name: acmschedule-svc
  namespace: acm-production
  resourceVersion: "24698553"
  uid: c6728769-dad5-4dbd-a372-b4328c440383
spec:
  clusterIP: 10.111.50.196
  clusterIPs:
  - 10.111.50.196
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31808
    port: 80
    protocol: TCP
    targetPort: 10060
  selector:
    app: acmschedule
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
