apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
  creationTimestamp: "2023-02-27T06:54:28Z"
  labels:
    app: acmservice-monitor
  name: acmservice-monitor-svc
  namespace: acm-production
  resourceVersion: "23565986"
  uid: 6e1474ca-cb23-42a0-a2b3-483b9e78fa54
spec:
  clusterIP: 10.104.181.170
  clusterIPs:
  - 10.104.181.170
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31398
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: acmservice-monitor
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
