apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
  creationTimestamp: "2023-02-27T06:54:29Z"
  labels:
    app: acmstatic-web
  name: acmstatic-web-svc
  namespace: acm-production
  resourceVersion: "23565996"
  uid: 85b75ee3-9314-4409-9336-5e43fd3a56b4
spec:
  clusterIP: 10.105.175.136
  clusterIPs:
  - 10.105.175.136
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30994
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: acmstatic-web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
