apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
  creationTimestamp: "2023-02-27T06:54:29Z"
  labels:
    app: acmtemplate
  name: acmtemplate-svc
  namespace: acm-production
  resourceVersion: "23566001"
  uid: 91469260-6236-491a-9d02-6cdcd79dd78e
spec:
  clusterIP: 10.109.135.244
  clusterIPs:
  - 10.109.135.244
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31072
    port: 80
    protocol: TCP
    targetPort: 11061
  selector:
    app: acmtemplate
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
