apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
  creationTimestamp: "2023-02-27T06:54:29Z"
  labels:
    app: acmwebhookservice
  name: acmwebhookservice-svc
  namespace: acm-production
  resourceVersion: "23566008"
  uid: 6ad6e580-155c-4366-b642-15786ec07149
spec:
  clusterIP: 10.108.15.205
  clusterIPs:
  - 10.108.15.205
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31656
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: acmwebhookservice
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
