apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-27T06:54:29Z"
  labels:
    app: axnadmin
  name: axnadmin-svc
  namespace: acm-production
  resourceVersion: "24697324"
  uid: 602e466c-9006-4389-b7d4-0673856873e0
spec:
  clusterIP: 10.96.53.153
  clusterIPs:
  - 10.96.53.153
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30995
    port: 80
    protocol: TCP
    targetPort: 10057
  selector:
    app: axnadmin
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
