apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-03-08T09:05:27Z"
  labels:
    app: axnnotification
  name: axnnotification-svc
  namespace: acm-production
  resourceVersion: "24692983"
  uid: 02e1aca6-9bab-4afa-95da-3ea0b3b4cbee
spec:
  clusterIP: 10.102.131.100
  clusterIPs:
  - 10.102.131.100
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30777
    port: 80
    protocol: TCP
    targetPort: 11057
  selector:
    app: axnnotification
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
