apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
  creationTimestamp: "2023-02-27T06:54:30Z"
  labels:
    app: deeplink-web
  name: deeplink-web-svc
  namespace: acm-production
  resourceVersion: "23566046"
  uid: f7f0994f-8c52-4cb9-b200-74f03a61bfa8
spec:
  clusterIP: 10.103.105.234
  clusterIPs:
  - 10.103.105.234
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31186
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: deeplink-web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
