apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-27T04:24:15Z"
  name: glusterfs-cluster
  namespace: acm-production
  resourceVersion: "23552390"
  uid: 9e4c694d-98d0-40b8-b637-a2a783fc7401
spec:
  clusterIP: 10.110.159.50
  clusterIPs:
  - 10.110.159.50
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 1
    protocol: TCP
    targetPort: 1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
