apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "51"
  creationTimestamp: "2021-07-28T15:24:19Z"
  generation: 51
  labels:
    app: acm-api
  name: acm-api-dep
  namespace: default
  resourceVersion: "121097204"
  uid: 83723662-637a-469e-8374-58805c6584a9
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acm-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acm-api
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acm-api-config
        image: registry.awing.vn/acm-production/acm-api:2.0.84
        imagePullPolicy: IfNotPresent
        name: acm-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /acmResources
          name: acmstatic
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - glusterfs:
          endpoints: glusterfs-cluster
          path: gv-acm
        name: acmstatic
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2023-03-10T01:30:30Z"
    lastUpdateTime: "2023-03-10T01:30:30Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-07-28T15:24:19Z"
    lastUpdateTime: "2023-04-25T06:59:47Z"
    message: ReplicaSet "acm-api-dep-57ff985fc7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 51
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
