apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
  creationTimestamp: "2021-06-09T19:32:27Z"
  generation: 11
  labels:
    app: acmadsworker
  name: acmadsworker-dep
  namespace: default
  resourceVersion: "116572328"
  uid: 0b37938e-e6ec-44a6-a09a-6e4ed09f6247
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmadsworker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmadsworker
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmadsworker-config
        image: registry.awing.vn/acm-production/acmadsworker:2.0.19
        imagePullPolicy: IfNotPresent
        name: acmadsworker
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-03-09T15:25:07Z"
    lastUpdateTime: "2023-03-09T15:25:07Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-06-09T19:32:27Z"
    lastUpdateTime: "2023-03-30T16:03:43Z"
    message: ReplicaSet "acmadsworker-dep-7b99f49899" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 11
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
