apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2021-07-28T15:24:44Z"
  generation: 2
  labels:
    app: acmbase
  name: acmbase-dep
  namespace: default
  resourceVersion: "112848023"
  uid: d6be9e9c-53ad-42ec-906c-e89b03f96842
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmbase
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmbase
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmbase-config
        image: registry.awing.vn/acm-production/acmbase-svc:2.0.2
        imagePullPolicy: IfNotPresent
        name: acmbase
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2023-03-09T15:25:09Z"
    lastUpdateTime: "2023-03-09T15:25:09Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-07-28T15:24:44Z"
    lastUpdateTime: "2023-03-09T15:33:02Z"
    message: ReplicaSet "acmbase-dep-6467bb674" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
