apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "42"
  creationTimestamp: "2021-06-09T19:32:51Z"
  generation: 53
  labels:
    app: acmcaptive-web
  name: acmcaptive-web-dep
  namespace: default
  resourceVersion: "124708332"
  uid: 8ece5504-9ac1-43c7-a133-2823fdc05e98
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmcaptive-web
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmcaptive-web
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - acmcaptive-web
            topologyKey: kubernetes.io/hostname
      containers:
      - envFrom:
        - configMapRef:
            name: acmcaptive-web-config
        image: registry.awing.vn/acm-production/acmcaptive-web:2.1.3
        imagePullPolicy: IfNotPresent
        name: acmcaptive-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-04-06T08:38:06Z"
    lastUpdateTime: "2023-04-06T08:38:06Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-06-09T19:32:51Z"
    lastUpdateTime: "2023-05-17T04:24:08Z"
    message: ReplicaSet "acmcaptive-web-dep-55955b7b45" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 53
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
