apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "24"
  creationTimestamp: "2022-12-02T04:34:05Z"
  generation: 28
  labels:
    app: acmcaptive-v2-web
  name: acmcaptive-v2-web-dep
  namespace: default
  resourceVersion: "127356759"
  uid: 7cc4026b-cd60-49b1-a509-a79f763cca0e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmcaptive-v2-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmcaptive-v2-web
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmcaptive-v2-web-config
        image: registry.awing.vn/acm-production/acmcaptive-cna-android-web:1.0.65
        imagePullPolicy: IfNotPresent
        name: acmcaptive-v2-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-03-30T16:31:38Z"
    lastUpdateTime: "2023-03-30T16:31:38Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-12-02T04:34:05Z"
    lastUpdateTime: "2023-06-02T04:47:17Z"
    message: ReplicaSet "acmcaptive-v2-web-dep-779cbb9f79" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 28
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
