apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2021-07-28T15:18:11Z"
  generation: 5
  labels:
    app: acmdirectory
  name: acmdirectory-dep
  namespace: default
  resourceVersion: "112846677"
  uid: e17bc22e-a7ec-4b2d-ac68-4ab601b979a0
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmdirectory
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmdirectory
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmdirectory-config
        image: registry.awing.vn/acm-production/acmdirectory:2.0.6
        imagePullPolicy: IfNotPresent
        name: acmdirectory
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2021-07-28T15:18:11Z"
    lastUpdateTime: "2022-08-26T06:43:03Z"
    message: ReplicaSet "acmdirectory-dep-6c7f6cc5cf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-03-09T15:25:01Z"
    lastUpdateTime: "2023-03-09T15:25:01Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
