apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "12"
  creationTimestamp: "2022-12-19T10:07:24Z"
  generation: 14
  labels:
    app: acmid-api
  name: acmid-api-dep
  namespace: default
  resourceVersion: "121096981"
  uid: e0af32f5-05b2-4d06-9135-ff90acb67bb9
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmid-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmid-api
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmid-api-config
        image: registry.awing.vn/acm-production/acmid-api:1.0.18
        imagePullPolicy: IfNotPresent
        name: acmid-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /acmResources
          name: acmstatic
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - glusterfs:
          endpoints: glusterfs-cluster
          path: gv-acm
        name: acmstatic
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-04-25T06:32:16Z"
    lastUpdateTime: "2023-04-25T06:32:16Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-12-19T10:07:24Z"
    lastUpdateTime: "2023-04-25T06:58:43Z"
    message: ReplicaSet "acmid-api-dep-6c66b55778" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 14
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
