apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
  creationTimestamp: "2022-12-19T10:08:31Z"
  generation: 11
  labels:
    app: acmid-web
  name: acmid-web-dep
  namespace: default
  resourceVersion: "120192661"
  uid: 7043b9ca-62c5-4fab-8374-4134bff1409d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmid-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmid-web
    spec:
      containers:
      - image: registry.awing.vn/acm-production/acmid-web:2.1.23
        imagePullPolicy: IfNotPresent
        name: acmid-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/config.js
          name: aonconfigmap
          readOnly: true
          subPath: config.js
        - mountPath: /acmResources
          name: acmstatic
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: acmid-web-config
        name: aonconfigmap
      - glusterfs:
          endpoints: glusterfs-cluster
          path: gv-acm
        name: acmstatic
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-12-19T10:08:31Z"
    lastUpdateTime: "2023-02-15T04:57:01Z"
    message: ReplicaSet "acmid-web-dep-7dc44cdb9b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-03-09T15:25:27Z"
    lastUpdateTime: "2023-03-09T15:25:27Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 11
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
