apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "30"
  creationTimestamp: "2021-06-09T19:33:19Z"
  generation: 34
  labels:
    app: acmplacestatsforecast
  name: acmplacestatsforecast-dep
  namespace: default
  resourceVersion: "128348997"
  uid: 362e3395-00d2-4e3a-a31c-b522840f20f4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmplacestatsforecast
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmplacestatsforecast
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmplacestatsforecast-config
        image: registry.awing.vn/acm-production/acmplacestatsforecast-svc:2.0.31
        imagePullPolicy: IfNotPresent
        name: acmplacestatsforecast
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-06-09T19:33:19Z"
    lastUpdateTime: "2023-03-20T04:20:30Z"
    message: ReplicaSet "acmplacestatsforecast-dep-7fcc6d4958" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-06-08T05:00:11Z"
    lastUpdateTime: "2023-06-08T05:00:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 34
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
