apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "12"
  creationTimestamp: "2021-06-09T19:33:40Z"
  generation: 14
  labels:
    app: acmresourceforecast
  name: acmresourceforecast-dep
  namespace: default
  resourceVersion: "129175203"
  uid: 5b78b221-7595-4b14-b991-7a3f462b5100
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmresourceforecast
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmresourceforecast
    spec:
      containers:
      - image: registry.awing.vn/acm-production/acmresourceforecast-svc:3.0.2
        imagePullPolicy: IfNotPresent
        name: acmresourceforecast
        resources:
          limits:
            cpu: "10"
            memory: 20G
          requests:
            cpu: "8"
            memory: 16G
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
        - mountPath: /acmresourceforecast/acm_resource_forecast/config.py
          name: config
          subPath: config.py
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
      - configMap:
          defaultMode: 420
          name: acmresourceforecast-config
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-06-09T19:33:40Z"
    lastUpdateTime: "2023-04-14T10:11:25Z"
    message: ReplicaSet "acmresourceforecast-dep-9bf68f99c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-06-13T05:00:11Z"
    lastUpdateTime: "2023-06-13T05:00:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 14
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
