apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
  creationTimestamp: "2021-10-07T10:35:34Z"
  generation: 8
  labels:
    app: acmservice-monitor
  name: acmservice-monitor-dep
  namespace: default
  resourceVersion: "112846892"
  uid: 3d13dd43-b02d-41ae-a508-ac608d326d4a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmservice-monitor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmservice-monitor
    spec:
      containers:
      - image: registry.awing.vn/acm-production/acmservice-monitor:1.0.14
        imagePullPolicy: IfNotPresent
        name: acmservice-monitor
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
        - mountPath: /app/appsettings.json
          name: appsettings
          subPath: appsettings.json
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
      - configMap:
          defaultMode: 420
          name: acmservice-monitor-config
        name: appsettings
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-10-07T10:35:34Z"
    lastUpdateTime: "2022-10-24T08:29:31Z"
    message: ReplicaSet "acmservice-monitor-dep-5f59dbd45c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-03-09T15:25:15Z"
    lastUpdateTime: "2023-03-09T15:25:15Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 8
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
