apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "30"
  creationTimestamp: "2021-07-28T15:50:01Z"
  generation: 30
  labels:
    app: acmschedulecalculation
  name: acmschedulecalculation-dep
  namespace: default
  resourceVersion: "129091769"
  uid: 5f65d24f-4dd6-48f5-b37a-5ebfe7e9b1e1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmschedulecalculation
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmschedulecalculation
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmschedulecalculation-config
        image: registry.awing.vn/acm-production/acmschedulecalculation-svc:2.0.36
        imagePullPolicy: IfNotPresent
        name: acmschedulecalculation
        resources:
          limits:
            cpu: "5"
            memory: 10000Mi
          requests:
            cpu: "4"
            memory: 8000Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-07-28T15:50:01Z"
    lastUpdateTime: "2023-03-30T16:06:50Z"
    message: ReplicaSet "acmschedulecalculation-dep-7fdd6f99f5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-06-12T16:55:24Z"
    lastUpdateTime: "2023-06-12T16:55:24Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 30
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
