apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
  creationTimestamp: "2022-11-16T15:14:39Z"
  generation: 5
  labels:
    app: acmsolver
  name: acmsolver-dep
  namespace: default
  resourceVersion: "129091103"
  uid: 8a3ec44d-6d90-4629-b304-5dda42f87181
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmsolver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmsolver
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmsolver-config
        image: registry.awing.vn/acm-production/acmsolver-svc:2.0.69
        imagePullPolicy: IfNotPresent
        name: acmsolver
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-11-16T15:14:40Z"
    lastUpdateTime: "2022-12-21T04:06:24Z"
    message: ReplicaSet "acmsolver-dep-c885c979f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-06-12T16:50:20Z"
    lastUpdateTime: "2023-06-12T16:50:20Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
