apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
  creationTimestamp: "2021-06-09T19:33:51Z"
  generation: 8
  labels:
    app: acmschedule
  name: acmschedule-dep
  namespace: default
  resourceVersion: "112849395"
  uid: 6f35c28f-d096-4f4a-b561-d8c5c0632f47
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmschedule
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmschedule
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmschedule-config
        image: registry.awing.vn/acm-production/acmschedule:2.0.35
        imagePullPolicy: IfNotPresent
        name: acmschedule
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2023-03-09T15:24:57Z"
    lastUpdateTime: "2023-03-09T15:24:57Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-06-09T19:33:51Z"
    lastUpdateTime: "2023-03-09T15:39:00Z"
    message: ReplicaSet "acmschedule-dep-796d9d9b95" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 8
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
