apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
  creationTimestamp: "2021-06-09T19:33:46Z"
  generation: 7
  labels:
    app: acmsaga
  name: acmsaga-dep
  namespace: default
  resourceVersion: "112849114"
  uid: b5dbfa4a-5ed6-4d65-bea3-b4165fa32b94
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmsaga
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmsaga
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmsaga-config
        image: registry.awing.vn/acm-production/acmsaga:2.0.6
        imagePullPolicy: IfNotPresent
        name: acmsaga
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2023-03-09T15:24:51Z"
    lastUpdateTime: "2023-03-09T15:24:51Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-06-09T19:33:46Z"
    lastUpdateTime: "2023-03-09T15:38:10Z"
    message: ReplicaSet "acmsaga-dep-57987f4447" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 7
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
