apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
  creationTimestamp: "2021-07-28T15:20:38Z"
  generation: 13
  labels:
    app: acmtemplate
  name: acmtemplate-dep
  namespace: default
  resourceVersion: "112846749"
  uid: 3e6ef85d-ae82-4642-b2be-01221dce4265
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmtemplate
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmtemplate
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmtemplate-config
        image: registry.awing.vn/acm-production/acmtemplate-svc:2.0.11
        imagePullPolicy: IfNotPresent
        name: acmtemplate
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2021-07-28T15:20:38Z"
    lastUpdateTime: "2022-09-15T09:19:58Z"
    message: ReplicaSet "acmtemplate-dep-d5d79c844" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-03-09T15:25:05Z"
    lastUpdateTime: "2023-03-09T15:25:05Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 13
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
