apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "51"
  creationTimestamp: "2021-08-02T04:03:04Z"
  generation: 57
  labels:
    app: axn-web
  name: axn-web-dep
  namespace: default
  resourceVersion: "126035507"
  uid: c552e537-facd-4b92-b0c0-7523389b7aec
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: axn-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: axn-web
    spec:
      containers:
      - image: registry.awing.vn/acm-production/axn-web:2.1.8
        imagePullPolicy: IfNotPresent
        name: axn-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/config.js
          name: aonconfigmap
          readOnly: true
          subPath: config.js
        - mountPath: /acmResources
          name: acmstatic
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: axn-web-config
        name: aonconfigmap
      - glusterfs:
          endpoints: glusterfs-cluster
          path: gv-acm
        name: acmstatic
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2023-05-25T04:27:17Z"
    lastUpdateTime: "2023-05-25T04:27:17Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-05-25T04:19:19Z"
    lastUpdateTime: "2023-05-25T05:00:07Z"
    message: ReplicaSet "axn-web-dep-84d4c8f5bc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 57
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
