apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "43"
  creationTimestamp: "2021-06-09T19:34:15Z"
  generation: 45
  labels:
    app: axn-api
  name: axn-api-dep
  namespace: default
  resourceVersion: "125882737"
  uid: 1cbac3fa-402d-4f04-ba56-89a4be9364bc
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: axn-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: axn-api
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: axn-api-config
        image: registry.awing.vn/acm-production/axn-api:2.0.76
        imagePullPolicy: IfNotPresent
        name: axn-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /acmResources
          name: awingstatic
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - glusterfs:
          endpoints: glusterfs-cluster
          path: gv-acm
        name: awingstatic
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2021-06-09T21:08:38Z"
    lastUpdateTime: "2023-05-15T07:51:06Z"
    message: ReplicaSet "axn-api-dep-7749fc597d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-24T07:04:06Z"
    lastUpdateTime: "2023-05-24T07:04:06Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 45
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
