apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
  creationTimestamp: "2021-06-09T19:34:24Z"
  generation: 6
  labels:
    app: axnadmin
  name: axnadmin-dep
  namespace: default
  resourceVersion: "116571703"
  uid: 166bdcbc-45c5-411b-840a-4264d52da6fd
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: axnadmin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: axnadmin
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: axnadmin-config
        image: registry.awing.vn/acm-production/axnadmin:2.0.19
        imagePullPolicy: IfNotPresent
        name: axnadmin
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2023-03-09T15:25:02Z"
    lastUpdateTime: "2023-03-09T15:25:02Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-06-09T19:34:24Z"
    lastUpdateTime: "2023-03-30T16:01:10Z"
    message: ReplicaSet "axnadmin-dep-dfb85d499" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
