apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "10"
  creationTimestamp: "2021-06-09T19:34:29Z"
  generation: 10
  labels:
    app: axncampaign
  name: axncampaign-dep
  namespace: default
  resourceVersion: "116610902"
  uid: b3e069cb-dd59-4619-b59e-322d83f82efb
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: axncampaign
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: axncampaign
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - axncampaign
            topologyKey: kubernetes.io/hostname
      containers:
      - envFrom:
        - configMapRef:
            name: axncampaign-config
        image: registry.awing.vn/acm-production/acmcampaign:2.0.14
        imagePullPolicy: IfNotPresent
        name: axncampaign
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2021-06-09T19:34:29Z"
    lastUpdateTime: "2023-03-30T16:00:35Z"
    message: ReplicaSet "axncampaign-dep-546695b55c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-03-30T21:09:35Z"
    lastUpdateTime: "2023-03-30T21:09:35Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 10
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
