apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2021-06-09T19:34:34Z"
  generation: 5
  labels:
    app: axnnotification
  name: axnnotification-dep
  namespace: default
  resourceVersion: "112851599"
  uid: 71a9cb13-1bb3-481d-9537-a60d4f4f7628
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: axnnotification
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: axnnotification
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: axnnotification-config
        image: registry.awing.vn/acm-production/axnnotification-svc:2.0.3
        imagePullPolicy: IfNotPresent
        name: axnnotification
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-06-09T19:34:34Z"
    lastUpdateTime: "2023-03-09T15:44:05Z"
    message: ReplicaSet "axnnotification-dep-77fd68f69c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-03-09T15:50:57Z"
    lastUpdateTime: "2023-03-09T15:50:57Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
