apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "11"
  creationTimestamp: "2022-01-13T10:15:21Z"
  generation: 11
  labels:
    app: deeplink-web
  name: deeplink-web-dep
  namespace: default
  resourceVersion: "126228935"
  uid: 34275fc0-dd35-429d-ba02-3da10e1d5d40
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: deeplink-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deeplink-web
    spec:
      containers:
      - image: registry.awing.vn/acm-production/deeplink:2.1.8
        imagePullPolicy: IfNotPresent
        name: deeplink-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-03-09T15:24:36Z"
    lastUpdateTime: "2023-03-09T15:24:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-01-13T10:15:21Z"
    lastUpdateTime: "2023-05-26T09:00:15Z"
    message: ReplicaSet "deeplink-web-dep-6c6869d7db" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 11
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
