apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2023-03-30T15:35:34Z"
  generation: 3
  labels:
    app: taskscheduler
  name: taskscheduler-dep
  namespace: default
  resourceVersion: "119900711"
  uid: 72447ff7-6fe4-4b89-85cb-c6fece1f6470
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: taskscheduler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: taskscheduler
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: taskscheduler-config
        image: registry.awing.vn/acm-production/taskscheduler-svc:1.0.9
        imagePullPolicy: IfNotPresent
        name: taskscheduler
        resources:
          limits:
            cpu: "2"
            memory: 4G
          requests:
            cpu: "2"
            memory: 4G
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-03-30T15:35:49Z"
    lastUpdateTime: "2023-03-30T15:35:49Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-03-30T15:35:34Z"
    lastUpdateTime: "2023-04-18T11:37:20Z"
    message: ReplicaSet "taskscheduler-dep-cddbfcc68" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
