apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "56"
  creationTimestamp: "2021-07-28T15:23:23Z"
  generation: 56
  labels:
    app: acm-web
  name: acm-web-dep
  namespace: default
  resourceVersion: "126049546"
  uid: fd21d9f1-fdff-4dbb-871a-2b552f7ae84f
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acm-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acm-web
    spec:
      containers:
      - image: registry.awing.vn/acm-production/acm:2.1.7
        imagePullPolicy: IfNotPresent
        name: acm-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/config.js
          name: aonconfigmap
          readOnly: true
          subPath: config.js
        - mountPath: /acmResources
          name: acmstatic
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: acm-web-config
        name: aonconfigmap
      - glusterfs:
          endpoints: glusterfs-cluster
          path: gv-acm
        name: acmstatic
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2023-03-09T15:24:45Z"
    lastUpdateTime: "2023-03-09T15:24:45Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-07-28T15:23:23Z"
    lastUpdateTime: "2023-05-25T07:01:07Z"
    message: ReplicaSet "acm-web-dep-84995c99fc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 56
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
