apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "17"
  creationTimestamp: "2022-11-16T15:03:38Z"
  generation: 17
  labels:
    app: acm-cplex-solver
  name: acm-cplex-solver-dep
  namespace: default
  resourceVersion: "129091152"
  uid: ca01aaaf-7715-497b-8d30-53f8b00697e4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acm-cplex-solver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acm-cplex-solver
    spec:
      containers:
      - image: registry.awing.vn/acm-production/acm-cplex-solver-svc:1.0.18
        imagePullPolicy: IfNotPresent
        name: acm-cplex-solver
        resources:
          limits:
            cpu: "15"
            memory: 60G
          requests:
            cpu: "15"
            memory: 60G
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
        - mountPath: /acm-cplex-solver/acm_cplex_solver/config.py
          name: config
          subPath: config.py
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
      - configMap:
          defaultMode: 420
          name: acm-cplex-solver-config
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-11-16T15:03:38Z"
    lastUpdateTime: "2023-03-15T05:36:54Z"
    message: ReplicaSet "acm-cplex-solver-dep-6878d45cd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-06-12T16:50:25Z"
    lastUpdateTime: "2023-06-12T16:50:25Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 17
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
