apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "15"
  creationTimestamp: "2021-06-09T19:32:16Z"
  generation: 33
  labels:
    app: acmadpcronservice
  name: acmadpcronservice-dep
  namespace: default
  resourceVersion: "116587480"
  uid: 1f3583a5-8573-4051-a573-b56a324b6941
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmadpcronservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmadpcronservice
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmadpcronservice-config
        image: registry.awing.vn/acm-production/acmadpcronservice:2.0.36
        imagePullPolicy: IfNotPresent
        name: acmadpcronservice
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2023-03-30T17:37:52Z"
    lastUpdateTime: "2023-03-30T17:37:52Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-06-09T19:32:16Z"
    lastUpdateTime: "2023-03-30T17:59:50Z"
    message: ReplicaSet "acmadpcronservice-dep-698c96db5d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 33
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
