apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-06-09T19:02:05Z"
  generation: 3
  labels:
    name: freeradius
  name: acmfreeradius-dep
  namespace: default
  resourceVersion: "112846924"
  uid: bdb1f431-52d9-498d-ab63-584a6065137f
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 2
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      name: freeradius
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: freeradius
    spec:
      containers:
      - image: freeradius/freeradius-server
        imagePullPolicy: Always
        name: freeradius
        ports:
        - containerPort: 1812
          protocol: UDP
        - containerPort: 1813
          protocol: UDP
        resources:
          limits:
            cpu: "1"
            memory: 2000Mi
          requests:
            cpu: 10m
            memory: 10Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/raddb/clients.conf
          name: freeradius-clients
          subPath: clients.conf
        - mountPath: /etc/raddb/users
          name: freeradius-users
          subPath: users
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: clients
            path: clients.conf
          name: config-map-freeradius-clients
        name: freeradius-clients
      - configMap:
          defaultMode: 420
          items:
          - key: users
            path: users
          name: config-map-freeradius-users
        name: freeradius-users
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2023-03-09T15:21:03Z"
    lastUpdateTime: "2023-03-09T15:21:03Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
