apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
  creationTimestamp: "2021-06-09T19:34:01Z"
  generation: 5
  labels:
    app: acmstatic-web
  name: acmstatic-web-dep
  namespace: default
  resourceVersion: "112846467"
  uid: fbc85495-8702-4bb6-8ce5-019b70a4eab7
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmstatic-web
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmstatic-web
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - acmstatic-web
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.awing.vn/acm-production/acmstatic-web:1.2
        imagePullPolicy: IfNotPresent
        name: acmstatic-web
        resources:
          limits:
            cpu: "1"
            memory: 2000Mi
          requests:
            cpu: "1"
            memory: 2000Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/nginx/html/Files/
          name: awingstatic
        - mountPath: /etc/localtime
          name: awingtimezone
        - mountPath: /etc/nginx/nginx.conf
          name: acmstatic-web-config
          readOnly: true
          subPath: nginx.conf
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - glusterfs:
          endpoints: glusterfs-cluster
          path: gv-acm
        name: awingstatic
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
      - configMap:
          defaultMode: 420
          name: acmstatic-web-config
        name: acmstatic-web-config
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2021-06-09T21:08:54Z"
    lastUpdateTime: "2021-10-17T13:32:17Z"
    message: ReplicaSet "acmstatic-web-dep-b57d6c775" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-03-09T15:24:49Z"
    lastUpdateTime: "2023-03-09T15:24:49Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
