apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "10"
  creationTimestamp: "2023-02-27T09:16:01Z"
  generation: 10
  labels:
    app: acm-cplex-solver
  name: acm-cplex-solver-dep
  namespace: acm-production
  resourceVersion: "34854928"
  uid: c194d4dc-9d44-4bbf-aa09-84a15fba1c99
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acm-cplex-solver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acm-cplex-solver
    spec:
      containers:
      - image: registry.awing.vn/acm-production/acm-cplex-solver-svc:1.0.23
        imagePullPolicy: IfNotPresent
        name: acm-cplex-solver
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
        - mountPath: /acm-cplex-solver/acm_cplex_solver/config.py
          name: config
          subPath: config.py
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
      - configMap:
          defaultMode: 420
          name: acm-cplex-solver-config
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-02-27T09:16:01Z"
    lastUpdateTime: "2023-03-14T06:55:19Z"
    message: ReplicaSet "acm-cplex-solver-dep-85676569c4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-24T10:10:30Z"
    lastUpdateTime: "2023-05-24T10:10:30Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 10
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
