apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
  creationTimestamp: "2023-02-27T09:40:54Z"
  generation: 8
  labels:
    app: acmads
  name: acmads-dep
  namespace: acm-production
  resourceVersion: "34863363"
  uid: 74fee3cf-90f5-4fc5-9a92-1bcd6a551750
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmads
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmads
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmads-config
        image: registry.awing.vn/acm-production/acmads:2.0.24
        imagePullPolicy: IfNotPresent
        name: acmads
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-03-08T10:39:36Z"
    lastUpdateTime: "2023-05-17T09:54:27Z"
    message: ReplicaSet "acmads-dep-75b9df895" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-24T11:17:16Z"
    lastUpdateTime: "2023-05-24T11:17:16Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 8
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
