apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-02-27T09:24:06Z"
  generation: 1
  labels:
    app: acmadmin
  name: acmadmin-dep
  namespace: acm-production
  resourceVersion: "32690150"
  uid: a10947fe-d77d-4881-b2a6-c96616ad4b96
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmadmin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmadmin
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmadmin-config
        image: registry.awing.vn/acm-production/acmadmin-svc:2.0.5
        imagePullPolicy: IfNotPresent
        name: acmadmin
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-02-27T09:24:06Z"
    lastUpdateTime: "2023-02-27T09:24:16Z"
    message: ReplicaSet "acmadmin-dep-6b4848bd77" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-08T11:34:50Z"
    lastUpdateTime: "2023-05-08T11:34:50Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
