apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2023-02-27T09:40:27Z"
  generation: 2
  labels:
    app: acmbase
  name: acmbase-dep
  namespace: acm-production
  resourceVersion: "34865309"
  uid: 0ef19fed-f4b4-478c-a55f-f2aacbf495d5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmbase
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmbase
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmbase-config
        image: registry.awing.vn/acm-production/acmbase-svc:2.0.2
        imagePullPolicy: IfNotPresent
        name: acmbase
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-02-27T09:40:27Z"
    lastUpdateTime: "2023-03-08T09:54:28Z"
    message: ReplicaSet "acmbase-dep-6f7b67cf6b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-24T11:18:27Z"
    lastUpdateTime: "2023-05-24T11:18:27Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
