apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-02-27T09:36:25Z"
  generation: 1
  labels:
    app: acmcronservice
  name: acmcronservice-dep
  namespace: acm-production
  resourceVersion: "32675589"
  uid: 893d090b-e6c7-4d42-8a3e-46f1432741fb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmcronservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmcronservice
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmcronservice-config
        image: registry.awing.vn/acm-production/acmcronservice:2.0.19
        imagePullPolicy: IfNotPresent
        name: acmcronservice
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-02-27T09:36:25Z"
    lastUpdateTime: "2023-02-27T09:36:34Z"
    message: ReplicaSet "acmcronservice-dep-78f8f4fc9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-08T09:47:22Z"
    lastUpdateTime: "2023-05-08T09:47:22Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
