apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2023-02-27T09:38:18Z"
  generation: 3
  labels:
    app: acmcampaign
  name: acmcampaign-dep
  namespace: acm-production
  resourceVersion: "34865384"
  uid: e60bdd41-a25d-4439-9431-6c6934a905fa
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmcampaign
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmcampaign
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmcampaign-config
        image: registry.awing.vn/acm-production/acmcampaign:2.0.14
        imagePullPolicy: IfNotPresent
        name: acmcampaign
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-02-27T09:38:18Z"
    lastUpdateTime: "2023-03-30T09:06:30Z"
    message: ReplicaSet "acmcampaign-dep-7768b964b6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-24T11:18:31Z"
    lastUpdateTime: "2023-05-24T11:18:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
