apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-02-27T09:35:03Z"
  generation: 1
  labels:
    app: acmdirectory
  name: acmdirectory-dep
  namespace: acm-production
  resourceVersion: "34865537"
  uid: 6405ef49-e488-4080-8242-38770231552c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmdirectory
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmdirectory
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmdirectory-config
        image: registry.awing.vn/acm-production/acmdirectory:2.0.6
        imagePullPolicy: IfNotPresent
        name: acmdirectory
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-02-27T09:35:03Z"
    lastUpdateTime: "2023-02-27T09:35:10Z"
    message: ReplicaSet "acmdirectory-dep-79cfcbb95f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-24T11:18:39Z"
    lastUpdateTime: "2023-05-24T11:18:39Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
