apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
  creationTimestamp: "2023-02-27T09:42:41Z"
  generation: 6
  labels:
    app: acmid-api
  name: acmid-api-dep
  namespace: acm-production
  resourceVersion: "34863118"
  uid: 5a6f4a38-52c0-461f-98f9-844506b35796
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmid-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmid-api
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmid-api-config
        image: registry.awing.vn/acm-production/acmid-api:1.0.18
        imagePullPolicy: IfNotPresent
        name: acmid-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /acmResources
          name: acmstatic
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - glusterfs:
          endpoints: glusterfs-cluster
          path: gv-acm
        name: acmstatic
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-02-27T09:42:41Z"
    lastUpdateTime: "2023-04-25T06:48:48Z"
    message: ReplicaSet "acmid-api-dep-79cfb684bb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-24T11:16:58Z"
    lastUpdateTime: "2023-05-24T11:16:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
