apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2023-02-27T10:31:05Z"
  generation: 3
  labels:
    app: acmid-web
  name: acmid-web-dep
  namespace: acm-production
  resourceVersion: "32676508"
  uid: a79949f7-e8b8-4202-809e-495328d18a11
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmid-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmid-web
    spec:
      containers:
      - image: registry.awing.vn/acm-production/acmid-web:2.1.24
        imagePullPolicy: IfNotPresent
        name: acmid-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/config.js
          name: aonconfigmap
          readOnly: true
          subPath: config.js
        - mountPath: /acmResources
          name: acmstatic
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: acmid-web-config
        name: aonconfigmap
      - glusterfs:
          endpoints: glusterfs-cluster
          path: gv-acm
        name: acmstatic
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-02-27T10:31:05Z"
    lastUpdateTime: "2023-02-27T11:32:25Z"
    message: ReplicaSet "acmid-web-dep-869dc7b4c7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-08T09:48:07Z"
    lastUpdateTime: "2023-05-08T09:48:07Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
