apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2023-02-27T09:35:55Z"
  generation: 4
  labels:
    app: acmplace
  name: acmplace-dep
  namespace: acm-production
  resourceVersion: "34865464"
  uid: 8b7fd01c-afa8-4e68-a806-832960e29068
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmplace
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmplace
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmplace-config
        image: registry.awing.vn/acm-production/acmplace:2.0.29
        imagePullPolicy: IfNotPresent
        name: acmplace
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-02-27T09:35:55Z"
    lastUpdateTime: "2023-03-30T09:07:41Z"
    message: ReplicaSet "acmplace-dep-d477c68bb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-24T11:18:35Z"
    lastUpdateTime: "2023-05-24T11:18:35Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
