apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2023-02-27T09:35:32Z"
  generation: 8
  labels:
    app: acmplacestatsforecast
  name: acmplacestatsforecast-dep
  namespace: acm-production
  resourceVersion: "29579187"
  uid: a6c33edc-b8d0-43c2-aedc-d6cefe141ea8
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmplacestatsforecast
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmplacestatsforecast
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmplacestatsforecast-config
        image: registry.awing.vn/acm-production/acmplacestatsforecast-svc:2.0.32
        imagePullPolicy: IfNotPresent
        name: acmplacestatsforecast
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  conditions:
  - lastTransitionTime: "2023-02-27T09:35:32Z"
    lastUpdateTime: "2023-03-30T09:09:26Z"
    message: ReplicaSet "acmplacestatsforecast-dep-85579f4459" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-04-14T09:19:08Z"
    lastUpdateTime: "2023-04-14T09:19:08Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 8
