apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-02-27T09:38:44Z"
  generation: 1
  labels:
    app: acmremarketing
  name: acmremarketing-dep
  namespace: acm-production
  resourceVersion: "32690274"
  uid: d0d5dfad-a27c-4ccc-bebb-62d10f597d11
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmremarketing
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmremarketing
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmremarketing-config
        image: registry.awing.vn/acm-production/acmremarketing-svc:2.0.3
        imagePullPolicy: IfNotPresent
        name: acmremarketing
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-02-27T09:38:44Z"
    lastUpdateTime: "2023-02-27T09:38:55Z"
    message: ReplicaSet "acmremarketing-dep-74b8b6fbf9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-08T11:34:57Z"
    lastUpdateTime: "2023-05-08T11:34:57Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
