apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "13"
  creationTimestamp: "2022-10-03T08:06:47Z"
  generation: 33
  labels:
    app: acmresourceforecast
  name: acmresourceforecast-dep
  namespace: acm-production
  resourceVersion: "34865347"
  uid: 63b8b6e5-f4cf-4106-8b06-228c6a213b42
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmresourceforecast
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmresourceforecast
    spec:
      containers:
      - image: registry.awing.vn/acm-dev/acmresourceforecast-svc:256
        imagePullPolicy: IfNotPresent
        name: acmresourceforecast
        resources:
          limits:
            cpu: "2"
            memory: 16000Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
        - mountPath: /acmresourceforecast/acm_resource_forecast/config.py
          name: config
          subPath: config.py
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-dev-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
      - configMap:
          defaultMode: 420
          name: acmresourceforecast-config
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-10-03T08:06:47Z"
    lastUpdateTime: "2023-03-07T10:45:37Z"
    message: ReplicaSet "acmresourceforecast-dep-5465684dc6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-24T11:18:29Z"
    lastUpdateTime: "2023-05-24T11:18:29Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 33
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
