apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2023-02-27T09:12:38Z"
  generation: 2
  labels:
    app: acmstatic-web
  name: acmstatic-web-dep
  namespace: acm-production
  resourceVersion: "34865695"
  uid: 8c6e3296-4a27-4c94-a30c-03b034aafac1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmstatic-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmstatic-web
    spec:
      containers:
      - image: registry.awing.vn/acm-production/acmstatic-web:1.2
        imagePullPolicy: IfNotPresent
        name: acmstatic-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/nginx/html/Files/
          name: acmstatic
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - glusterfs:
          endpoints: glusterfs-cluster
          path: gv-acm
        name: acmstatic
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-02-27T09:12:38Z"
    lastUpdateTime: "2023-02-27T09:13:04Z"
    message: ReplicaSet "acmstatic-web-dep-56b7fcc8fc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-24T11:18:47Z"
    lastUpdateTime: "2023-05-24T11:18:47Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
