apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2023-02-27T09:32:47Z"
  generation: 3
  labels:
    app: acmschedule
  name: acmschedule-dep
  namespace: acm-production
  resourceVersion: "34865324"
  uid: 7ec7b958-a9b1-4aef-add7-773eb63b50b8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmschedule
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmschedule
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmschedule-config
        image: registry.awing.vn/acm-production/acmschedule:2.0.35
        imagePullPolicy: IfNotPresent
        name: acmschedule
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-03-08T10:33:55Z"
    lastUpdateTime: "2023-03-08T10:36:48Z"
    message: ReplicaSet "acmschedule-dep-74b6b898f9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-24T11:18:28Z"
    lastUpdateTime: "2023-05-24T11:18:28Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
