apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2023-02-27T09:34:29Z"
  generation: 3
  labels:
    app: acmsaga
  name: acmsaga-dep
  namespace: acm-production
  resourceVersion: "32675393"
  uid: 6cdb2979-c08b-4cbf-998f-154fc6f21297
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmsaga
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmsaga
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmsaga-config
        image: registry.awing.vn/acm-production/acmsaga:2.0.6
        imagePullPolicy: IfNotPresent
        name: acmsaga
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-03-08T10:41:49Z"
    lastUpdateTime: "2023-03-08T10:41:53Z"
    message: ReplicaSet "acmsaga-dep-6fd7d6c9bc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-08T09:47:17Z"
    lastUpdateTime: "2023-05-08T09:47:17Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
