apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-02-27T09:30:58Z"
  generation: 1
  labels:
    app: acmtemplate
  name: acmtemplate-dep
  namespace: acm-production
  resourceVersion: "34865642"
  uid: cfbfcbc0-e35a-4837-8eb0-68433e9e7e5f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmtemplate
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmtemplate
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmtemplate-config
        image: registry.awing.vn/acm-production/acmtemplate-svc:2.0.11
        imagePullPolicy: IfNotPresent
        name: acmtemplate
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-02-27T09:30:58Z"
    lastUpdateTime: "2023-02-27T09:31:06Z"
    message: ReplicaSet "acmtemplate-dep-5b9fc5889b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-24T11:18:45Z"
    lastUpdateTime: "2023-05-24T11:18:45Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
