apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2023-02-27T09:30:21Z"
  generation: 2
  labels:
    app: acmwebhook
  name: acmwebhook-dep
  namespace: acm-production
  resourceVersion: "34863042"
  uid: f899cb20-449d-47a1-80a1-e7e30439496d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acmwebhook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acmwebhook
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: acmwebhookservice-config
        image: registry.awing.vn/acm-production/acmwebhook-svc:2.0.10
        imagePullPolicy: IfNotPresent
        name: acmwebhook
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-02-27T09:30:21Z"
    lastUpdateTime: "2023-02-27T09:31:41Z"
    message: ReplicaSet "acmwebhook-dep-5c6fb84f96" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-24T11:16:55Z"
    lastUpdateTime: "2023-05-24T11:16:55Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
