apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "19"
  creationTimestamp: "2023-02-27T09:42:11Z"
  generation: 19
  labels:
    app: axn-api
  name: axn-api-dep
  namespace: acm-production
  resourceVersion: "34863109"
  uid: e3c63e47-d486-482d-a4fb-149b3a21941f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: axn-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: axn-api
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: axn-api-config
        image: registry.awing.vn/acm-production/axn-api:2.0.76
        imagePullPolicy: IfNotPresent
        name: axn-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /acmResources
          name: axnstatic
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - glusterfs:
          endpoints: glusterfs-cluster
          path: gv-acm
        name: axnstatic
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-02-27T09:42:11Z"
    lastUpdateTime: "2023-05-15T07:12:20Z"
    message: ReplicaSet "axn-api-dep-cdd48fdfd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-24T11:16:57Z"
    lastUpdateTime: "2023-05-24T11:16:57Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 19
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
