apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
  creationTimestamp: "2023-02-27T09:32:06Z"
  generation: 5
  labels:
    app: axnadmin
  name: axnadmin-dep
  namespace: acm-production
  resourceVersion: "34865488"
  uid: c0b08d25-f901-4e4b-8b4e-36c8bc3524b8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: axnadmin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: axnadmin
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: axnadmin-config
        image: registry.awing.vn/acm-production/axnadmin:2.0.19
        imagePullPolicy: IfNotPresent
        name: axnadmin
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-02-27T09:32:06Z"
    lastUpdateTime: "2023-03-30T10:29:47Z"
    message: ReplicaSet "axnadmin-dep-9b5748c5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-24T11:18:36Z"
    lastUpdateTime: "2023-05-24T11:18:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
