apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2023-02-27T09:28:59Z"
  generation: 3
  labels:
    app: axncampaign
  name: axncampaign-dep
  namespace: acm-production
  resourceVersion: "34865332"
  uid: 9d7b10a4-ba31-4c9b-963f-4acdd6d797a2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: axncampaign
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: axncampaign
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: axncampaign-config
        image: registry.awing.vn/acm-production/acmcampaign:2.0.14
        imagePullPolicy: IfNotPresent
        name: axncampaign
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-02-27T09:28:59Z"
    lastUpdateTime: "2023-03-30T09:06:37Z"
    message: ReplicaSet "axncampaign-dep-6f67459d8d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-24T11:18:29Z"
    lastUpdateTime: "2023-05-24T11:18:29Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
