apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2023-02-27T09:29:43Z"
  generation: 4
  labels:
    app: axnplace
  name: axnplace-dep
  namespace: acm-production
  resourceVersion: "34865293"
  uid: fe7de4aa-3717-4890-9368-83f05a1c3c06
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: axnplace
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: axnplace
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: axnplace-config
        image: registry.awing.vn/acm-production/axnplace:2.0.15
        imagePullPolicy: IfNotPresent
        name: axnplace
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-02-27T09:29:43Z"
    lastUpdateTime: "2023-04-19T10:36:44Z"
    message: ReplicaSet "axnplace-dep-7bd9cf48b7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-24T11:18:27Z"
    lastUpdateTime: "2023-05-24T11:18:27Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
