apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-04-07T07:03:25Z"
  generation: 2
  labels:
    app: old-acmplacestatsforecast
  name: old-acmplacestatsforecast-dep
  namespace: acm-production
  resourceVersion: "29577869"
  uid: 2625b803-56d7-463c-a008-595423016fd5
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: old-acmplacestatsforecast
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: old-acmplacestatsforecast
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: old-acmplacestatsforecast-config
        image: registry.awing.vn/acm-production/acmplacestatsforecast-svc:2.old.7
        imagePullPolicy: IfNotPresent
        name: old-acmplacestatsforecast
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  conditions:
  - lastTransitionTime: "2023-04-07T07:03:25Z"
    lastUpdateTime: "2023-04-07T07:03:27Z"
    message: ReplicaSet "old-acmplacestatsforecast-dep-5484b644b8" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-04-07T09:35:36Z"
    lastUpdateTime: "2023-04-07T09:35:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
