apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-04-07T03:56:37Z"
  generation: 2
  labels:
    app: old-acmresourceforecast
  name: old-acmresourceforecast-dep
  namespace: acm-production
  resourceVersion: "29577886"
  uid: 3ebfeaae-f1b5-44b8-b030-a2a38703d45f
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: old-acmresourceforecast
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: old-acmresourceforecast
    spec:
      containers:
      - image: registry.awing.vn/acm-production/acmresourceforecast-svc:2.0.3
        imagePullPolicy: IfNotPresent
        name: old-acmresourceforecast
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
        - mountPath: /acmresourceforecast/acm_resource_forecast/config.py
          name: config
          subPath: config.py
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
      - configMap:
          defaultMode: 420
          name: old-acmresourceforecast-config
        name: config
status:
  conditions:
  - lastTransitionTime: "2023-04-07T03:56:37Z"
    lastUpdateTime: "2023-04-07T03:56:38Z"
    message: ReplicaSet "old-acmresourceforecast-dep-d6d6859cf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-04-08T18:51:54Z"
    lastUpdateTime: "2023-04-08T18:51:54Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
