apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "15"
  creationTimestamp: "2023-03-30T09:35:42Z"
  generation: 15
  labels:
    app: taskscheduler
  name: taskscheduler-dep
  namespace: acm-production
  resourceVersion: "32690284"
  uid: 9b35a433-762c-471f-bcd7-a6a01a60f17e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: taskscheduler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: taskscheduler
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: taskscheduler-config
        image: registry.awing.vn/acm-production/taskscheduler-svc:1.0.9
        imagePullPolicy: IfNotPresent
        name: taskscheduler
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: awingtimezone
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-production-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: awingtimezone
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-03-30T09:35:42Z"
    lastUpdateTime: "2023-04-14T10:12:21Z"
    message: ReplicaSet "taskscheduler-dep-6789d4698" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-08T11:34:58Z"
    lastUpdateTime: "2023-05-08T11:34:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 15
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
