apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-07-28T15:24:11Z"
  labels:
    app: acm-api
  name: acm-api-svc
  namespace: default
  resourceVersion: "8728645"
  uid: 1603469d-61a9-4573-9622-5f7912368950
spec:
  clusterIP: 10.97.50.128
  clusterIPs:
  - 10.97.50.128
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30185
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: acm-api
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
