apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-07-28T15:22:48Z"
  labels:
    app: acm-web
  name: acm-web-svc
  namespace: default
  resourceVersion: "8728398"
  uid: 6bb83e37-8a59-4dfb-bee7-403f306876bc
spec:
  clusterIP: 10.98.75.84
  clusterIPs:
  - 10.98.75.84
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30721
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: acm-web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
