apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-09T19:07:27Z"
  labels:
    app: acmadmin
  name: acmadmin-svc
  namespace: default
  resourceVersion: "7486"
  uid: 9a83cace-1d11-4fb7-8715-efb2b36d93e1
spec:
  clusterIP: 10.100.29.241
  clusterIPs:
  - 10.100.29.241
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32217
    port: 80
    protocol: TCP
    targetPort: 10052
  selector:
    app: acmadmin
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
