apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-09T19:25:59Z"
  labels:
    app: acmplace
  name: acmplace-svc
  namespace: default
  resourceVersion: "9875"
  uid: c98973ee-0b19-43ba-865f-96234316bc09
spec:
  clusterIP: 10.110.252.40
  clusterIPs:
  - 10.110.252.40
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31280
    port: 80
    protocol: TCP
    targetPort: 10053
  selector:
    app: acmplace
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
