apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-04-26T07:46:26Z"
  labels:
    app: acmremarketing
  name: acmremarketing-svc
  namespace: default
  resourceVersion: "56766168"
  uid: 756a0804-891a-4df5-b9cf-bcca1df7137e
spec:
  clusterIP: 10.109.68.55
  clusterIPs:
  - 10.109.68.55
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31764
    port: 80
    protocol: TCP
    targetPort: 11066
  selector:
    app: acmremarketing
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
