apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-09T19:26:37Z"
  labels:
    app: acmstatic-web
  name: acmstatic-web-svc
  namespace: default
  resourceVersion: "9983"
  uid: f9e734a0-f33c-4a6f-b216-e3dba8d832a3
spec:
  clusterIP: 10.105.175.136
  clusterIPs:
  - 10.105.175.136
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30994
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: acmstatic-web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
