apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-07-28T15:19:50Z"
  labels:
    app: acmtemplate
  name: acmtemplate-svc
  namespace: default
  resourceVersion: "35562558"
  uid: d700a63d-4da7-4f53-8dcf-76f08e57a1f6
spec:
  clusterIP: 10.109.135.244
  clusterIPs:
  - 10.109.135.244
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31072
    port: 80
    protocol: TCP
    targetPort: 11061
  selector:
    app: acmtemplate
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
