apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-09T19:26:41Z"
  labels:
    app: acmwebhookservice
  name: acmwebhookservice-svc
  namespace: default
  resourceVersion: "10000"
  uid: 1869fd54-8003-438d-9caf-720846b0e951
spec:
  clusterIP: 10.108.15.205
  clusterIPs:
  - 10.108.15.205
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31656
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: acmwebhookservice
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
