apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-03-30T15:35:34Z"
  labels:
    app: taskscheduler
  name: taskscheduler-svc
  namespace: default
  resourceVersion: "116568169"
  uid: d4631587-64be-4f0f-b231-f2f2e1c5efc0
spec:
  clusterIP: 10.110.9.53
  clusterIPs:
  - 10.110.9.53
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31193
    port: 80
    protocol: TCP
    targetPort: 10099
  selector:
    app: taskscheduler
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
