apiVersion: v1
data:
  AcmCronConfiguration__Grpc__AcmAdminTarget: http://acmadmin-svc.default:80
  AcmCronConfiguration__Kafka__BootstrapServers: 192.168.10.25:9092,192.168.10.35:9092,192.168.10.45:9092
  AcmCronConfiguration__Service__PlaceStatsDayOfWeekCalculate: Sunday
  AcmCronConfiguration__Service__PlaceStatsIntervalDay: "7"
  AcmCronConfiguration__Service__ScheduleIntervalHour: "2"
  AcmCronConfiguration__Service__SleepTimeInSecond: "60"
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-09T19:21:13Z"
  labels:
    app: acmcronservice
  name: acmcronservice-config
  namespace: default
  resourceVersion: "108694475"
  uid: 7f465621-ed58-4511-92b5-3247f9b6aabd
