apiVersion: v1
data:
  CaptiveConfiguration__CheckInternetLink: http://awifi.vn/Picture/1x1pixel.png
  CaptiveConfiguration__TokenSecretKey: Acm@Awing
  ConnectionStrings__KafkaConnection: 192.168.10.25:9092,192.168.10.35:9092,192.168.10.45:9092
  Grpc__AcmAdminTarget: http://acmadmin-svc.default:80
  Grpc__AcmAdpTarget: http://acmadp-svc.default:80
  Grpc__AcmAdsTarget: http://acmads-svc.default:80
  Grpc__AcmCampaignTarget: http://acmcampaign-svc.default:80
  Grpc__AcmPlaceTarget: http://acmplace-svc.default:80
  Grpc__AcmTemplateTarget: http://acmtemplate-svc.default:80
  Grpc__AxnCampaignTarget: http://axncampaign-svc.default:80
  Logging__LogLevel__AcmCaptive.Models.CustomerActionRepo: None
  Logging__LogLevel__AcmCaptive.Tasks.AnalyticProducerWorker: None
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-09T19:21:08Z"
  labels:
    app: acmcaptive-web
  name: acmcaptive-web-config
  namespace: default
  resourceVersion: "111154341"
  uid: 0ffa0f1f-5d94-4599-ae48-39c1bab7b30b
