apiVersion: v1
data:
  AcmPlaceConfiguration__DatabaseConnectionString: Server=192.168.10.54;Port=3306;Database=acmPlace;user
    id=acm;password=Awing@2018;CharSet=utf8;
  AcmPlaceConfiguration__GrpcHost: 0.0.0.0
  AcmPlaceConfiguration__GrpcPort: "10053"
  AcmPlaceConfiguration__MaxTotalTasks: "4"
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-09T19:21:31Z"
  labels:
    app: acmplace
  name: acmplace-config
  namespace: default
  resourceVersion: "4006501"
  uid: b3ab19c0-f11e-4ded-a00d-6bb25ae0e7c9
