apiVersion: v1
data:
  config.py: "GRPC_MAX_WORKER = 10\nconnection_str =\"mongodb://192.168.10.24:27017,192.168.10.34:27017,192.168.10.44:27017/\"
    \ndb_name = \"acmResourceForecast\"\nFORECAST_MAX_WORKER =  6\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-09T19:21:50Z"
  name: acmresourceforecast-config
  namespace: default
  resourceVersion: "104167646"
  uid: c749f5be-2273-4b45-b08f-f5941fa52442
