apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: "2022-03-14T10:44:39Z"
  name: deleting-pod-acmschedulecalculation
  namespace: default
  resourceVersion: "129091853"
  uid: 4a0b1bee-cb07-4ca5-b1e1-b676e7f01e23
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      activeDeadlineSeconds: 600
      backoffLimit: 2
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - kubectl delete pod $(kubectl get pod -l app=acmschedulecalculation -o
              jsonpath="{.items[0].metadata.name}")
            command:
            - /bin/sh
            - -c
            image: bitnami/kubectl
            imagePullPolicy: Always
            name: kubectl
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: deleting-pods
          serviceAccountName: deleting-pods
          terminationGracePeriodSeconds: 30
  schedule: 55 16 * * 1
  successfulJobsHistoryLimit: 3
  suspend: false
status:
  lastScheduleTime: "2023-06-12T16:55:00Z"
