apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: "2022-03-14T10:43:28Z"
  name: deleting-pod-acmsolver
  namespace: default
  resourceVersion: "129091114"
  uid: 759ebaea-c195-413b-b457-7b4b4f9aa28d
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      activeDeadlineSeconds: 600
      backoffLimit: 2
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - kubectl delete pod $(kubectl get pod -l app=acmsolver -o jsonpath="{.items[0].metadata.name}")
            command:
            - /bin/sh
            - -c
            image: bitnami/kubectl
            imagePullPolicy: Always
            name: kubectl
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: deleting-pods
          serviceAccountName: deleting-pods
          terminationGracePeriodSeconds: 30
  schedule: 50 16 * * 1
  successfulJobsHistoryLimit: 3
  suspend: false
status:
  lastScheduleTime: "2023-06-12T16:50:00Z"
