apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-11-16T15:03:18Z"
  labels:
    app: acm-cplex-solver
  name: acm-cplex-solver-svc
  namespace: default
  resourceVersion: "92901776"
  uid: b5a7c256-bb58-4f8a-8a8c-99d8a50e0c13
spec:
  clusterIP: 10.102.207.60
  clusterIPs:
  - 10.102.207.60
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32312
    port: 80
    protocol: TCP
    targetPort: 50051
  selector:
    app: acm-cplex-solver
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
