apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-09T19:24:43Z"
  labels:
    app: acmapis
  name: acmapis-svc
  namespace: default
  resourceVersion: "9581"
  uid: 253caae2-3255-466f-b2a5-cb75ac1fdebf
spec:
  clusterIP: 10.97.57.202
  clusterIPs:
  - 10.97.57.202
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31076
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: acmapis
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
