apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-09T19:24:31Z"
  labels:
    app: acmadp
  name: acmadp-svc
  namespace: default
  resourceVersion: "9548"
  uid: c48d3210-db6a-4bea-b339-676b23703d5a
spec:
  clusterIP: 10.107.85.81
  clusterIPs:
  - 10.107.85.81
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32168
    port: 80
    protocol: TCP
    targetPort: 10055
  selector:
    app: acmadp
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
