apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-09T19:24:37Z"
  labels:
    run: acmads
  name: acmads-svc
  namespace: default
  resourceVersion: "9562"
  uid: d8a94ee1-4bc9-4a84-bf7d-865d520e54e0
spec:
  clusterIP: 10.102.252.123
  clusterIPs:
  - 10.102.252.123
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31648
    port: 80
    protocol: TCP
    targetPort: 10056
  selector:
    app: acmads
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
