apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-07-28T15:24:35Z"
  labels:
    app: acmbase
  name: acmbase-svc
  namespace: default
  resourceVersion: "8728744"
  uid: 40d2325c-f111-402f-a5fc-93c555bad3f8
spec:
  clusterIP: 10.99.146.160
  clusterIPs:
  - 10.99.146.160
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32679
    port: 80
    protocol: TCP
    targetPort: 11062
  selector:
    app: acmbase
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
