apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-09T19:25:36Z"
  labels:
    app: acmcampaignmatchrate
  name: acmcampaignmatchrate-svc
  namespace: default
  resourceVersion: "9801"
  uid: 49cbf32e-8a61-426e-8196-8d3ff23c2c19
spec:
  clusterIP: 10.110.74.52
  clusterIPs:
  - 10.110.74.52
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32424
    port: 80
    protocol: TCP
    targetPort: 10069
  selector:
    app: acmcampaignmatchrate
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
