apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-09T19:24:48Z"
  labels:
    app: acmcampaign
  name: acmcampaign-svc
  namespace: default
  resourceVersion: "9602"
  uid: d8e5094e-0cdd-4bb5-8c86-6010484259ad
spec:
  clusterIP: 10.104.83.152
  clusterIPs:
  - 10.104.83.152
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30644
    port: 80
    protocol: TCP
    targetPort: 10054
  selector:
    app: acmcampaign
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
