apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-12-02T04:33:56Z"
  labels:
    app: acmcaptive-v2-web
  name: acmcaptive-v2-web-svc
  namespace: default
  resourceVersion: "95653268"
  uid: 6e3b2215-4daa-4272-a217-4a4500d3f1c4
spec:
  clusterIP: 10.106.212.135
  clusterIPs:
  - 10.106.212.135
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31559
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: acmcaptive-v2-web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
