apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-07-28T15:18:02Z"
  labels:
    app: acmdirectory
  name: acmdirectory-svc
  namespace: default
  resourceVersion: "8727461"
  uid: f5ef577f-14e6-4e36-889b-457528167ac0
spec:
  clusterIP: 10.106.169.53
  clusterIPs:
  - 10.106.169.53
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31752
    port: 80
    protocol: TCP
    targetPort: 11058
  selector:
    app: acmdirectory
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
