apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-12-19T10:08:21Z"
  labels:
    app: acmid-web
  name: acmid-web-svc
  namespace: default
  resourceVersion: "98705955"
  uid: 4f648a89-8688-450d-82c5-8e7f576082af
spec:
  clusterIP: 10.110.210.197
  clusterIPs:
  - 10.110.210.197
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32125
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: acmid-web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
