apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-12-19T10:07:17Z"
  labels:
    app: acmid-api
  name: acmid-api-svc
  namespace: default
  resourceVersion: "98705758"
  uid: c1856fd8-7c77-4467-bde1-acb0d1b58b81
spec:
  clusterIP: 10.104.84.194
  clusterIPs:
  - 10.104.84.194
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31493
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: acmid-api
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
