apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-09T19:26:05Z"
  labels:
    app: acmplacestatsforecast
  name: acmplacestatsforecast-svc
  namespace: default
  resourceVersion: "9890"
  uid: de1d1346-7ff6-4fbe-bbbb-8123db085746
spec:
  clusterIP: 10.104.245.53
  clusterIPs:
  - 10.104.245.53
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30073
    port: 80
    protocol: TCP
    targetPort: 10059
  selector:
    app: acmplacestatsforecast
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
