apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-09T19:26:16Z"
  labels:
    app: acmresourceforecast
  name: acmresourceforecast-svc
  namespace: default
  resourceVersion: "9922"
  uid: 3ddbed93-702f-4580-8bfd-effa58a35f72
spec:
  clusterIP: 10.105.210.159
  clusterIPs:
  - 10.105.210.159
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30423
    port: 80
    protocol: TCP
    targetPort: 50052
  selector:
    app: acmresourceforecast
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
