apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-07-28T15:49:23Z"
  labels:
    app: acmschedulecalculation
  name: acmschedulecalculation-svc
  namespace: default
  resourceVersion: "8732577"
  uid: a507207f-d18a-4083-a91d-80b8e87d9c99
spec:
  clusterIP: 10.111.197.19
  clusterIPs:
  - 10.111.197.19
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32169
    port: 80
    protocol: TCP
    targetPort: 10060
  selector:
    app: acmschedulecalculation
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
