apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-11-16T15:14:22Z"
  labels:
    app: acmsolver
  name: acmsolver-svc
  namespace: default
  resourceVersion: "92903414"
  uid: 47ee9419-1f63-4664-8cce-e6e74582c2e7
spec:
  clusterIP: 10.108.160.156
  clusterIPs:
  - 10.108.160.156
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30789
    port: 80
    protocol: TCP
    targetPort: 50051
  selector:
    app: acmsolver
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
