apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-09T19:26:47Z"
  labels:
    app: axn-api
  name: axn-api-svc
  namespace: default
  resourceVersion: "10015"
  uid: 9b5ddaff-2494-4a69-a58e-6c561e147671
spec:
  clusterIP: 10.108.75.26
  clusterIPs:
  - 10.108.75.26
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32693
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: axn-api
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
