apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-09T19:27:14Z"
  labels:
    app: axnplace
  name: axnplace-svc
  namespace: default
  resourceVersion: "10100"
  uid: 056ba1f1-716e-45ce-9c60-d20c04a0ab90
spec:
  clusterIP: 10.110.88.28
  clusterIPs:
  - 10.110.88.28
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30770
    port: 80
    protocol: TCP
    targetPort: 10059
  selector:
    app: axnplace
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
