apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-01-13T10:15:13Z"
  labels:
    app: deeplink-web
  name: deeplink-web-svc
  namespace: default
  resourceVersion: "38531160"
  uid: 192ec006-ddd3-4429-9f36-2286f06dda98
spec:
  clusterIP: 10.103.105.234
  clusterIPs:
  - 10.103.105.234
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31186
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: deeplink-web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
