apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-09T18:07:26Z"
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "211"
  uid: 240d908a-5d9c-40be-9b41-f0cc5dedbc7b
spec:
  clusterIP: 10.96.0.1
  clusterIPs:
  - 10.96.0.1
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
