apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-09T19:01:25Z"
  name: service-freeradius-accounting
  namespace: default
  resourceVersion: "117449783"
  uid: cbdc1f4e-1418-4cb5-b92e-c9c72eec57f5
spec:
  clusterIP: 10.98.173.112
  clusterIPs:
  - 10.98.173.112
  externalIPs:
  - 192.168.10.57
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: freeradius-accounting
    nodePort: 32121
    port: 1813
    protocol: UDP
    targetPort: 1813
  selector:
    name: freeradius
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
