apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-09T19:01:37Z"
  name: service-freeradius-authentication
  namespace: default
  resourceVersion: "117449728"
  uid: 56631e72-ae78-47eb-a8e0-084b8477874e
spec:
  clusterIP: 10.98.31.31
  clusterIPs:
  - 10.98.31.31
  externalIPs:
  - 192.168.10.57
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: freeradius-authentication
    nodePort: 30012
    port: 1812
    protocol: UDP
    targetPort: 1812
  selector:
    name: freeradius
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
